[package]
name = "auth-server"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
fnmock = "0.3.0"

serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
serde_urlencoded = "0.7.1"

thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }
url = "2.5.8"
uuid = { version="1.26.0", features=["v4", "serde"] }

api-macros = { version = "0.1.2", git = "https://github.com/jakob-rzeppa/Auth.git", branch = "main" }
chrono = { version = "0.4.45", features = ["serde"] }
redis = { version = "1.7.0", features = ["tokio-comp"] }
rand = "0.10.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
sha2 = "0.11.0"
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "macros", "uuid", "chrono", "sqlx-toml"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tower-http = { version = "0.7.1", features = ["trace"] }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
